language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: JoMOs9ZcH6vQUKwcMP6nr+/D+dEVoe9K6iwKG4wtgC3/TjZGgnPgrha9bN7mhxTGbP4AW7BTmq/1HEWaOxgbnE3vhZTsSH/dYZKPYoEGwBfvpkjqcqRwpCDHSshzJ+J3L75o8HkH+CSGn9hzukH7hGUVU36vRx9cVDZQwBVGUv0=
  app: offline-todo-api
  on:
    repo: matthew-andrews/offline-todo-api
    node: 0.10
